"""Small models hosted as GitHub release assets (first download source for them).

Models of up to a few hundred MB (the Opus-MT translation models, the SAGE clean-up model) are attached, file by file, to
the pre-release ``models-v1`` of the project repository.  ``model_release.json`` (next to this file, generated by
``tools/make_model_release.py``) pins the asset name, size and SHA-256 of every file, so nothing is trusted but the hash.
A model is taken from GitHub FIRST; if GitHub is slow or fails (the stall watchdog of :mod:`infra.download_watch`
abandons it) the caller falls back to the original Hugging Face repository, then our Hugging Face mirror, then ModelScope
(:func:`infra.model_downloader.ensure_model`).  Large models (hundreds of MB to GB) never use this source.

Downloads resume: data goes to ``<file>.incomplete`` (HTTP ``Range``) and is renamed only after the SHA-256 matched.
Standard library only (HTTPS through :mod:`infra.net`).
"""
from __future__ import annotations

import fnmatch
import hashlib
import json
import logging
import os
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Dict, Iterable, Optional

log = logging.getLogger("voxprint.models")

MANIFEST_PATH = Path(__file__).with_name("model_release.json")
SCHEMA = 1
CHUNK = 1024 * 1024
#: Largest model (sum of its files, bytes) that is hosted as release assets; bigger ones stay on Hugging Face / ModelScope.
SMALL_MODEL_MAX = 500 * 1000 * 1000
#: Set to 1 to disable only this source (``VOXPRINT_NO_MIRROR=1`` disables all mirrors).
ENV_DISABLE = "VOXPRINT_NO_GITHUB_MODELS"
#: ``open(request, timeout)`` returns a response object (injectable in tests).
Opener = Callable[[urllib.request.Request, float], Any]


class ReleaseError(Exception):
    """GitHub cannot supply a complete, hash-verified copy; the caller tries the next source."""


@dataclass(frozen=True)
class ReleaseEntry:
    """One model of the release: the commit it is identical to and its files (asset name, size, SHA-256)."""
    source_repo: str
    source_revision: str
    base_url: str                          # https://github.com/<owner>/<repo>/releases/download/<tag>
    files: Dict[str, Dict[str, Any]]       # relative posix path -> {"asset", "size", "sha256"}

    def selected(self, patterns: Optional[Iterable[str]] = None) -> Dict[str, Dict[str, Any]]:
        """Files of the model, limited by glob ``patterns`` (like ``allow_patterns``); a pattern that matches nothing = error."""
        pats = list(patterns or ())
        if not pats:
            return dict(self.files)
        missing = [p for p in pats if not any(fnmatch.fnmatchcase(n, p) for n in self.files)]
        if missing:
            raise ReleaseError(f"{self.source_repo}: no file in the release matches {', '.join(missing)}")
        return {n: m for n, m in self.files.items() if any(fnmatch.fnmatchcase(n, p) for p in pats)}

    def url(self, name: str) -> str:
        return f"{self.base_url}/{urllib.parse.quote(self.files[name]['asset'])}"

    def sizes(self, patterns: Optional[Iterable[str]] = None) -> Dict[str, int]:
        return {n: int(m["size"]) for n, m in self.selected(patterns).items()}


def enabled() -> bool:
    off = ("1", "true", "yes", "on")
    return (os.environ.get(ENV_DISABLE, "").strip().lower() not in off
            and os.environ.get("VOXPRINT_NO_MIRROR", "").strip().lower() not in off)


def _safe_name(name: str) -> bool:
    p = PurePosixPath(name)
    return bool(name) and not p.is_absolute() and ".." not in p.parts and "\\" not in name and ":" not in name


def load(path: Optional[Path] = None) -> Dict[str, ReleaseEntry]:
    """``{source_repo: ReleaseEntry}`` from the manifest; empty if it is missing or invalid (never raises)."""
    try:
        data = json.loads((path or MANIFEST_PATH).read_text(encoding="utf-8"))
        if data.get("schema") != SCHEMA:
            raise ValueError("unsupported schema")
        base = f"https://github.com/{data['repo']}/releases/download/{data['tag']}"
        base = str(data.get("base_url") or base).rstrip("/")
        out: Dict[str, ReleaseEntry] = {}
        for src, e in data["models"].items():
            files = e["files"]
            if not files or not all(_safe_name(n) and len(m["sha256"]) == 64 and int(m["size"]) >= 0 and m["asset"]
                                    and "/" not in m["asset"] for n, m in files.items()):
                raise ValueError(f"bad file list for {src}")
            out[src] = ReleaseEntry(src, e["source_revision"], base, files)
        return out
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as exc:
        log.warning("model release manifest unusable: %s", exc)
        return {}


def entry_for(repo_id: str, revision: Optional[str] = None, path: Optional[Path] = None) -> Optional[ReleaseEntry]:
    """Release entry of a model for exactly this revision (None = any), or None (not hosted / disabled / manifest unusable)."""
    if not enabled():
        return None
    e = load(path).get(repo_id)
    if e is None or (revision and e.source_revision != revision):
        return None
    return e


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 22), b""):
            h.update(block)
    return h.hexdigest()


def file_ok(path: Path, meta: Dict[str, Any]) -> bool:
    try:
        return path.is_file() and path.stat().st_size == int(meta["size"]) and sha256_file(path) == meta["sha256"]
    except OSError:
        return False


def _open(req: urllib.request.Request, timeout: float):
    from infra import net

    return net.urlopen(req, timeout)  # noqa: S310 - https to github.com only (the manifest base URL)


def fetch_file(url: str, target: Path, meta: Dict[str, Any], on_bytes: Callable[[int], None], opener: Opener,
                timeout: float) -> None:
    """Download one asset into ``target`` (resuming ``target.incomplete``) and verify it; raises ReleaseError."""
    size = int(meta["size"])
    part = target.with_name(target.name + ".incomplete")
    target.parent.mkdir(parents=True, exist_ok=True)
    have = part.stat().st_size if part.exists() else 0
    if have > size:
        part.unlink()
        have = 0
    if have < size:
        headers = {"User-Agent": "Voxprint"}
        if have:
            headers["Range"] = f"bytes={have}-"
            on_bytes(have)                                        # what is already on disk counts as done
        try:
            with opener(urllib.request.Request(url, headers=headers), timeout) as r:
                if have and getattr(r, "status", 200) != 206:          # the server ignored Range: start over
                    have = 0
                with open(part, "ab" if have else "wb") as f:
                    while True:
                        chunk = r.read(CHUNK)
                        if not chunk:
                            break
                        f.write(chunk)
                        on_bytes(len(chunk))
        except (OSError, urllib.error.URLError) as exc:
            raise ReleaseError(f"{url}: {exc}") from exc            # the .incomplete file stays: the next run resumes
    if part.stat().st_size != size:
        raise ReleaseError(f"{target.name}: incomplete ({part.stat().st_size} of {size} bytes)")
    if sha256_file(part) != meta["sha256"]:
        part.unlink()
        log.warning("%s from %s: SHA-256 mismatch, deleted", target.name, url.split("/")[2] if "//" in url else url)
        raise ReleaseError(f"{target.name}: SHA-256 mismatch with the manifest")
    os.replace(part, target)
    log.info("%s (%d bytes) from %s: SHA-256 OK", target.name, size, url.split("/")[2] if "//" in url else url)


def download(entry: ReleaseEntry, dest: Path, progress: Callable[[float], None] = lambda f: None,
             patterns: Optional[Iterable[str]] = None, opener: Optional[Opener] = None, timeout: float = 30.0) -> str:
    """Download the model's files into ``dest`` (resuming), verify every file's SHA-256 and return the commit sha they equal.

    Files already in ``dest`` with the right size and hash are kept.  Nothing unverified stays behind.
    """
    opener = opener or _open
    files = entry.selected(patterns)
    total = sum(int(m["size"]) for m in files.values()) or 1
    done = 0
    dest.mkdir(parents=True, exist_ok=True)
    for name, meta in sorted(files.items()):
        target = dest.joinpath(*PurePosixPath(name).parts)
        if file_ok(target, meta):
            done += int(meta["size"])
            progress(min(1.0, done / total))
            continue
        if target.exists():
            target.unlink()
        base = done

        def on_bytes(n: int, _b=[0]) -> None:  # noqa: B006 - per-file counter (a new function per file)
            _b[0] += n
            progress(min(1.0, (base + _b[0]) / total))  # noqa: B023 - called within this iteration

        fetch_file(entry.url(name), target, meta, on_bytes, opener, timeout)
        done += int(meta["size"])
        progress(min(1.0, done / total))
    return entry.source_revision
