"""Write a module that imports the WHOLE Python standard library, for PyInstaller's analysis only (it is never imported at run time).

Why: a PyInstaller build contains only the standard-library modules its own code imports.  The thin shell downloads PyTorch and ~70 other
libraries afterwards, and those import "everything" (``timeit``, ``unittest``, ``doctest``, ``sched`` ... - found by the CI end-to-end check:
``No module named 'timeit'``).  ``build_thin.bat`` generates this file with the build's own Python and passes ``--hidden-import _vx_stdlib``.

Usage: ``python tools/gen_stdlib_bundle.py <output dir>``  ->  ``<output dir>/_vx_stdlib.py``
"""
from __future__ import annotations

import sys
from pathlib import Path

#: Not useful in a download-able runtime (GUI toolkits we do not ship, tests, demos, interpreter internals that must not be imported).
SKIP = {"tkinter", "_tkinter", "idlelib", "turtledemo", "turtle", "test", "antigravity", "this", "__main__", "__hello__",
        "__phello__", "lib2to3", "ensurepip", "pydoc_data", "msilib", "_pyrepl", "_distutils_hack", "sre_compile", "sre_constants",
        "sre_parse"}


def modules() -> list:
    names = sorted(n for n in sys.stdlib_module_names if n not in SKIP and not n.startswith("_test"))
    return names


def render(names=None) -> str:
    names = modules() if names is None else names
    lines = ['"""Generated by tools/gen_stdlib_bundle.py - for PyInstaller\'s analysis only; never imported."""']
    for n in names:
        lines.append(f"try:\n    import {n}\nexcept Exception:  # noqa: BLE001\n    pass")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    out = Path(argv[0] if argv else "build/stdlib_bundle")
    out.mkdir(parents=True, exist_ok=True)
    (out / "_vx_stdlib.py").write_text(render(), encoding="utf-8")
    print(f"{len(modules())} standard-library modules -> {out / '_vx_stdlib.py'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
